# Generated by Django 5.0.4 on 2025-10-23 10:14

from django.db import migrations, models


def forwards_update_models(apps, schema_editor):
    Chat = apps.get_model("chat", "Chat")
    replacements = {
        "gpt-3.5-turbo": "gpt-4o-mini",
        "gpt-4": "gpt-4o",
    }
    for old_value, new_value in replacements.items():
        Chat.objects.filter(gpt_model=old_value).update(gpt_model=new_value)


def noop_reverse(apps, schema_editor):
    # Historical values no longer valid; keep upgraded selections.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chat_platform_model_name"),
    ]

    operations = [
        migrations.RunPython(forwards_update_models, noop_reverse),
        migrations.AlterField(
            model_name="chat",
            name="gpt_model",
            field=models.CharField(
                choices=[
                    ("gpt-4o-mini", "Gpt 4O Mini"),
                    ("gpt-4o", "Gpt 4O"),
                    ("gpt-5", "Gpt 5"),
                ],
                default="gpt-4o-mini",
                max_length=20,
            ),
        ),
    ]
