# Generated by Django 5.0.4 on 2024-05-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_options_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='gpt_model',
            field=models.CharField(choices=[('gpt-4', 'Gpt 4'), ('gpt-3.5-turbo', 'Gpt 3 5 Turbo')], default='gpt-3.5-turbo', max_length=20),
        ),
    ]
