# Generated by Django 5.0.4 on 2025-10-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_chat_gpt_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="chat_images/"),
        ),
    ]
