# Generated by Django 5.0.4 on 2024-05-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='gpt_model',
            field=models.CharField(choices=[('gpt-4', 'Gpt 4'), ('gpt-3.5-turbo', 'Gpt 3 5 Turbo'), ('gpt-4o', 'Gpt 4O')], default='gpt-3.5-turbo', max_length=20),
        ),
    ]
