# Generated by Django 5.0.4 on 2025-10-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_message_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="platform",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("gemini", "Gemini"),
                    ("mistral", "Mistral"),
                ],
                default="openai",
                max_length=10,
            ),
        ),
    ]
